apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  namespace: osm
  name: db
spec:
  imageName: ghcr.io/cloudnative-pg/postgis:15-3.4
  bootstrap:
    initdb:
      postInitTemplateSQL:
        - CREATE EXTENSION postgis;
        - CREATE EXTENSION postgis_topology;
      localeCollate: C.UTF-8
      localeCType: C.UTF-8
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 100Gi

  postgresql:
    parameters:
      max_connections: "32" # default 100
      shared_buffers: "6GB" # default 128MB
      effective_cache_size: "12GB" # default 4GB
      maintenance_work_mem: "2GB" # default 64MB
      checkpoint_completion_target: "0.9" # default 0.9
      wal_buffers: "16MB" # default 4MB
      default_statistics_target: "500" # default 100
      random_page_cost: "4" # default 4
      effective_io_concurrency: "2" # default 1
      work_mem: "16MB" # default 4MB
      huge_pages: "off" # default try
      min_wal_size: "4GB" # default 80MB
      max_wal_size: "16GB" # default 1GB
      max_worker_processes: "8" # default 32
      max_parallel_workers_per_gather: "4" # default 2
      max_parallel_workers: "8" # default 32
      max_parallel_maintenance_workers: "4" # default 2
  resources:
    requests:
      memory: "16Gi"
      cpu: 8
    limits:
      memory: "16Gi"
      cpu: 8

  managed:
    roles:
      - name: web_tileserv
        ensure: present
        login: true
        inherit: false
        passwordSecret:
          name: pg-tileserv-user
      - name: web_auth
        ensure: present
      - name: web_anon
        ensure: present
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  namespace: osm-airflow
  name: db
spec:
  bootstrap:
    initdb:
      localeCollate: C.UTF-8
      localeCType: C.UTF-8
  instances: 1
  primaryUpdateStrategy: unsupervised
  storage:
    size: 8Gi

  postgresql:
    parameters:
      max_connections: "32" # default 100
      shared_buffers: "128MB" # default 128MB
      effective_cache_size: "2GB" # default 4GB
      maintenance_work_mem: "64MB" # default 64MB
      checkpoint_completion_target: "0.9" # default 0.9
      wal_buffers: "4MB" # default 4MB
      default_statistics_target: "100" # default 100
      random_page_cost: "4" # default 4
      effective_io_concurrency: "2" # default 1
      work_mem: "4MB" # default 4MB
      huge_pages: "off" # default try
      min_wal_size: "80MB" # default 80MB
      max_wal_size: "1GB" # default 1GB
      max_worker_processes: "8" # default 32
      max_parallel_workers_per_gather: "2" # default 2
      max_parallel_workers: "8" # default 32
      max_parallel_maintenance_workers: "2" # default 2
  resources:
    requests:
      memory: "2Gi"
      cpu: 2
    limits:
      memory: "4Gi"
      cpu: 4
